# Generated by Django 3.0.5 on 2020-04-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_id', models.CharField(max_length=5)),
                ('breed', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=3)),
                ('pet_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.CharField(max_length=3)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=15)),
                ('mname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=15)),
                ('mobno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=5)),
                ('pet_name', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=6)),
                ('colour', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=6)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='p_image')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Breed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pet_type')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.CharField(max_length=4)),
                ('answer', models.CharField(max_length=50)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Que')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
